package org.tedros.common.domain;

import java.util.*;
import java.util.stream.Collectors;

/**
 * Enum com todos os MIME types conhecidos (fonte: mimetype.io/all-types)
 * Permite busca por extensão (case-insensitive) e retorna o MIME type.
 */
public enum MimeType {
    // === APPLICATION ===
    ANDREW_INSET("application/andrew-inset", "ez"),
    APPLIXWARE("application/applixware", "aw"),
    ATOM_XML("application/atom+xml", "atom"),
    ATOMCAT_XML("application/atomcat+xml", "atomcat"),
    ATOMSVC_XML("application/atomsvc+xml", "atomsvc"),
    CCXML_XML("application/ccxml+xml", "ccxml"),
    CU_SEEME("application/cu-seeme", "cu"),
    DAVMOUNT_XML("application/davmount+xml", "davmount"),
    ECMASCRIPT("application/ecmascript", "ecma"),
    EMMA_XML("application/emma+xml", "emma"),
    EPUB_ZIP("application/epub+zip", "epub"),
    FONT_TDPFR("application/font-tdpfr", "pfr"),
    GZIP("application/gzip", "gz", "tgz"),
    HYPERSTUDIO("application/hyperstudio", "stk"),
    JAVA_ARCHIVE("application/java-archive", "jar"),
    JAVA_SERIALIZED_OBJECT("application/java-serialized-object", "ser"),
    JAVA_VM("application/java-vm", "class"),
    JSON("application/json", "json"),
    LOST_XML("application/lost+xml", "lostxml"),
    MAC_BINHEX40("application/mac-binhex40", "hqx"),
    MAC_COMPACTPRO("application/mac-compactpro", "cpt"),
    MARC("application/marc", "mrc"),
    MATHEMATICA("application/mathematica", "ma", "mb", "nb"),
    MATHML_XML("application/mathml+xml", "mathml", "mml"),
    MBOX("application/mbox", "mbox"),
    MEDIASERVERCONTROL_XML("application/mediaservercontrol+xml", "mscml"),
    MP4S("application/mp4", "mp4s"),
    MSWORD("application/msword", "doc", "dot", "wiz"),
    MXF("application/mxf", "mxf"),
    OCTET_STREAM("application/octet-stream", "a", "bin", "bpk", "deploy", "dist", "distz", "dmg", "dms", "dump", "elc", "lha", "lrf", "lzh", "o", "obj", "pkg", "so"),
    ODA("application/oda", "oda"),
    OEBPS_PACKAGE_XML("application/oebps-package+xml", "opf"),
    OGX("application/ogg", "ogx"),
    ONENOTE("application/onenote", "onepkg", "onetmp", "onetoc", "onetoc2"),
    PATCH_OPS_ERROR_XML("application/patch-ops-error+xml", "xer"),
    PDF("application/pdf", "pdf"),
    PGP_ENCRYPTED("application/pgp-encrypted", "pgp"),
    PGP_SIGNATURE("application/pgp-signature", "asc", "sig"),
    PICS_RULES("application/pics-rules", "prf"),
    PKCS10("application/pkcs10", "p10"),
    PKCS7_MIME("application/pkcs7-mime", "p7c", "p7m"),
    PKCS7_SIGNATURE("application/pkcs7-signature", "p7s"),
    PKIX_CERT("application/pkix-cert", "cer"),
    PKIX_CRL("application/pkix-crl", "crl"),
    PKIX_PKIPATH("application/pkix-pkipath", "pkipath"),
    PKIXCMP("application/pkixcmp", "pki"),
    PLS_XML("application/pls+xml", "pls"),
    POSTSCRIPT("application/postscript", "ai", "eps", "ps"),
    PRQL("application/prql", "prql"),
    PRS_CWW("application/prs.cww", "cww"),
    RDF_XML("application/rdf+xml", "rdf"),
    REGINFO_XML("application/reginfo+xml", "rif"),
    RELAX_NG_COMPACT_SYNTAX("application/relax-ng-compact-syntax", "rnc"),
    RESOURCE_LISTS_XML("application/resource-lists+xml", "rl"),
    RESOURCE_LISTS_DIFF_XML("application/resource-lists-diff+xml", "rld"),
    RLS_SERVICES_XML("application/rls-services+xml", "rs"),
    RSD_XML("application/rsd+xml", "rsd"),
    RSS_XML("application/rss+xml", "rss", "xml"),
    RTF("application/rtf", "rtf"),
    SBML_XML("application/sbml+xml", "sbml"),
    SCVP_CV_REQUEST("application/scvp-cv-request", "scq"),
    SCVP_CV_RESPONSE("application/scvp-cv-response", "scs"),
    SCVP_VP_REQUEST("application/scvp-vp-request", "spq"),
    SCVP_VP_RESPONSE("application/scvp-vp-response", "spp"),
    SDP("application/sdp", "sdp"),
    SET_PAYMENT_INITIATION("application/set-payment-initiation", "setpay"),
    SET_REGISTRATION_INITIATION("application/set-registration-initiation", "setreg"),
    SHF_XML("application/shf+xml", "shf"),
    SMIL_XML("application/smil+xml", "smi", "smil"),
    SPARQL_QUERY("application/sparql-query", "rq"),
    SPARQL_RESULTS_XML("application/sparql-results+xml", "srx"),
    SRGS("application/srgs", "gram"),
    SRGS_XML("application/srgs+xml", "grxml"),
    SSML_XML("application/ssml+xml", "ssml"),
    VND_3GPP_PIC_BW_LARGE("application/vnd.3gpp.pic-bw-large", "plb"),
    VND_3GPP_PIC_BW_SMALL("application/vnd.3gpp.pic-bw-small", "psb"),
    VND_3GPP_PIC_BW_VAR("application/vnd.3gpp.pic-bw-var", "pvb"),
    VND_3GPP2_TCAP("application/vnd.3gpp2.tcap", "tcap"),
    VND_3M_POST_IT_NOTES("application/vnd.3m.post-it-notes", "pwn"),
    VND_ACCPAC_SIMPLY_ASO("application/vnd.accpac.simply.aso", "aso"),
    VND_ACCPAC_SIMPLY_IMP("application/vnd.accpac.simply.imp", "imp"),
    VND_ACUCOBOL("application/vnd.acucobol", "acu"),
    VND_ACUCORP("application/vnd.acucorp", "acutc", "atc"),
    VND_ADOBE_AIR_APPLICATION_INSTALLER_PACKAGE_ZIP("application/vnd.adobe.air-application-installer-package+zip", "air"),
    VND_ADOBE_XDP_XML("application/vnd.adobe.xdp+xml", "xdp"),
    VND_ADOBE_XFDF("application/vnd.adobe.xfdf", "xfdf"),
    VND_AIRZIP_FILESECURE_AZF("application/vnd.airzip.filesecure.azf", "azf"),
    VND_AIRZIP_FILESECURE_AZS("application/vnd.airzip.filesecure.azs", "azs"),
    VND_AMAZON_EBOOK("application/vnd.amazon.ebook", "azw"),
    VND_AMERICANDYNAMICS_ACC("application/vnd.americandynamics.acc", "acc"),
    VND_AMIGA_AMI("application/vnd.amiga.ami", "ami"),
    VND_ANDROID_PACKAGE_ARCHIVE("application/vnd.android.package-archive", "apk"),
    VND_ANSER_WEB_CERTIFICATE_ISSUE_INITIATION("application/vnd.anser-web-certificate-issue-initiation", "cii"),
    VND_ANSER_WEB_FUNDS_TRANSFER_INITIATION("application/vnd.anser-web-funds-transfer-initiation", "fti"),
    VND_ANTIX_GAME_COMPONENT("application/vnd.antix.game-component", "atx"),
    VND_APPLE_INSTALLER_XML("application/vnd.apple.installer+xml", "mpkg"),
    VND_ARASTRA_SWI("application/vnd.arastra.swi", "swi"),
    VND_AUDIOGRAPH("application/vnd.audiograph", "aep"),
    VND_BLUEICE_MULTIPASS("application/vnd.blueice.multipass", "mpm"),
    VND_BMI("application/vnd.bmi", "bmi"),
    VND_BUSINESSOBJECTS("application/vnd.businessobjects", "rep"),
    VND_CHEMDRAW_XML("application/vnd.chemdraw+xml", "cdxml"),
    VND_CHIPNUTS_KARAOKE_MMD("application/vnd.chipnuts.karaoke-mmd", "mmd"),
    VND_CINDERELLA("application/vnd.cinderella", "cdy"),
    VND_CLAYMORE("application/vnd.claymore", "cla"),
    VND_CLONK_C4GROUP("application/vnd.clonk.c4group", "c4d", "c4f", "c4g", "c4p", "c4u"),
    VND_COMMONSPACE("application/vnd.commonspace", "csp"),
    VND_CONTACT_CMSG("application/vnd.contact.cmsg", "cdbcmsg"),
    VND_COSMOCALLER("application/vnd.cosmocaller", "cmc"),
    VND_CRICK_CLICKER("application/vnd.crick.clicker", "clkx"),
    VND_CRICK_CLICKER_KEYBOARD("application/vnd.crick.clicker.keyboard", "clkk"),
    VND_CRICK_CLICKER_PALETTE("application/vnd.crick.clicker.palette", "clkp"),
    VND_CRICK_CLICKER_TEMPLATE("application/vnd.crick.clicker.template", "clkt"),
    VND_CRICK_CLICKER_WORDBANK("application/vnd.crick.clicker.wordbank", "clkw"),
    VND_CRITICALTOOLS_WBS_XML("application/vnd.criticaltools.wbs+xml", "wbs"),
    VND_CTC_POSML("application/vnd.ctc-posml", "pml"),
    VND_CUPS_PPD("application/vnd.cups-ppd", "ppd"),
    VND_CURL_CAR("application/vnd.curl.car", "car"),
    VND_CURL_PCURL("application/vnd.curl.pcurl", "pcurl"),
    VND_DATA_VISION_RDZ("application/vnd.data-vision.rdz", "rdz"),
    VND_DEBIAN_BINARY_PACKAGE("application/vnd.debian.binary-package", "deb", "udeb"),
    VND_DENOVO_FCSELAYOUT_LINK("application/vnd.denovo.fcselayout-link", "fe_launch"),
    VND_DNA("application/vnd.dna", "dna"),
    VND_DOLBY_MLP("application/vnd.dolby.mlp", "mlp"),
    VND_DPGRAPH("application/vnd.dpgraph", "dpg"),
    VND_DREAMFACTORY("application/vnd.dreamfactory", "dfac"),
    VND_DYNAGEO("application/vnd.dynageo", "geo"),
    VND_ECOWIN_CHART("application/vnd.ecowin.chart", "mag"),
    VND_ENLIVEN("application/vnd.enliven", "nml"),
    VND_EPSON_ESF("application/vnd.epson.esf", "esf"),
    VND_EPSON_MSF("application/vnd.epson.msf", "msf"),
    VND_EPSON_QUICKANIME("application/vnd.epson.quickanime", "qam"),
    VND_EPSON_SALT("application/vnd.epson.salt", "slt"),
    VND_EPSON_SSF("application/vnd.epson.ssf", "ssf"),
    VND_ESZIGNO3_XML("application/vnd.eszigno3+xml", "es3", "et3"),
    VND_EZPIX_ALBUM("application/vnd.ezpix-album", "ez2"),
    VND_EZPIX_PACKAGE("application/vnd.ezpix-package", "ez3"),
    VND_FDF("application/vnd.fdf", "fdf"),
    VND_FDSN_MSEED("application/vnd.fdsn.mseed", "mseed"),
    VND_FDSN_SEED("application/vnd.fdsn.seed", "dataless", "seed"),
    VND_FLOGRAPHIT("application/vnd.flographit", "gph"),
    VND_FLUXTIME_CLIP("application/vnd.fluxtime.clip", "ftc"),
    VND_FRAMEMAKER("application/vnd.framemaker", "book", "fm", "frame", "maker"),
    VND_FROGANS_FNC("application/vnd.frogans.fnc", "fnc"),
    VND_FROGANS_LTF("application/vnd.frogans.ltf", "ltf"),
    VND_FSC_WEBLAUNCH("application/vnd.fsc.weblaunch", "fsc"),
    VND_FUJITSU_OASYS("application/vnd.fujitsu.oasys", "oas"),
    VND_FUJITSU_OASYS2("application/vnd.fujitsu.oasys2", "oa2"),
    VND_FUJITSU_OASYS3("application/vnd.fujitsu.oasys3", "oa3"),
    VND_FUJITSU_OASYSGP("application/vnd.fujitsu.oasysgp", "fg5"),
    VND_FUJITSU_OASYSPRS("application/vnd.fujitsu.oasysprs", "bh2"),
    VND_FUJIXEROX_DDD("application/vnd.fujixerox.ddd", "ddd"),
    VND_FUJIXEROX_DOCUWORKS("application/vnd.fujixerox.docuworks", "xdw"),
    VND_FUJIXEROX_DOCUWORKS_BINDER("application/vnd.fujixerox.docuworks.binder", "xbd"),
    VND_FUZZYSHEET("application/vnd.fuzzysheet", "fzs"),
    VND_GENOMATIX_TUXEDO("application/vnd.genomatix.tuxedo", "txd"),
    VND_GEOGEBRA_FILE("application/vnd.geogebra.file", "ggb"),
    VND_GEOGEBRA_TOOL("application/vnd.geogebra.tool", "ggt"),
    VND_GEOMETRY_EXPLORER("application/vnd.geometry-explorer", "gex", "gre"),
    VND_GERBER("application/vnd.gerber", "gbr"),
    VND_GMX("application/vnd.gmx", "gmx"),
    VND_GOOGLE_EARTH_KML_XML("application/vnd.google-earth.kml+xml", "kml"),
    VND_GOOGLE_EARTH_KMZ("application/vnd.google-earth.kmz", "kmz"),
    VND_GRAFEQ("application/vnd.grafeq", "gqf", "gqs"),
    VND_GROOVE_ACCOUNT("application/vnd.groove-account", "gac"),
    VND_GROOVE_HELP("application/vnd.groove-help", "ghf"),
    VND_GROOVE_IDENTITY_MESSAGE("application/vnd.groove-identity-message", "gim"),
    VND_GROOVE_INJECTOR("application/vnd.groove-injector", "grv"),
    VND_GROOVE_TOOL_MESSAGE("application/vnd.groove-tool-message", "gtm"),
    VND_GROOVE_TOOL_TEMPLATE("application/vnd.groove-tool-template", "tpl"),
    VND_GROOVE_VCARD("application/vnd.groove-vcard", "vcg"),
    VND_HANDHELD_ENTERTAINMENT_XML("application/vnd.handheld-entertainment+xml", "zmm"),
    VND_HBCI("application/vnd.hbci", "hbci"),
    VND_HHE_LESSON_PLAYER("application/vnd.hhe.lesson-player", "les"),
    VND_HP_HPGL("application/vnd.hp-hpgl", "hpgl"),
    VND_HP_HPID("application/vnd.hp-hpid", "hpid"),
    VND_HP_HPS("application/vnd.hp-hps", "hps"),
    VND_HP_JLYT("application/vnd.hp-jlyt", "jlt"),
    VND_HP_PCL("application/vnd.hp-pcl", "pcl"),
    VND_HP_PCLXL("application/vnd.hp-pclxl", "pclxl"),
    VND_HYDROSTATIX_SOF_DATA("application/vnd.hydrostatix.sof-data", "sfd-hdstx"),
    VND_HZN_3D_CROSSWORD("application/vnd.hzn-3d-crossword", "x3d"),
    VND_IBM_MINIPAY("application/vnd.ibm.minipay", "mpy"),
    VND_IBM_MODCAP("application/vnd.ibm.modcap", "afp", "list3820", "listafp"),
    VND_IBM_RIGHTS_MANAGEMENT("application/vnd.ibm.rights-management", "irm"),
    VND_IBM_SECURE_CONTAINER("application/vnd.ibm.secure-container", "sc"),
    VND_ICCPROFILE("application/vnd.iccprofile", "icc", "icm"),
    VND_IGLOADER("application/vnd.igloader", "igl"),
    VND_IMMERVISION_IVP("application/vnd.immervision-ivp", "ivp"),
    VND_IMMERVISION_IVU("application/vnd.immervision-ivu", "ivu"),
    VND_INTERCON_FORMNET("application/vnd.intercon.formnet", "xpw", "xpx"),
    VND_INTU_QBO("application/vnd.intu.qbo", "qbo"),
    VND_INTU_QFX("application/vnd.intu.qfx", "qfx"),
    VND_IPUNPLUGGED_RCPROFILE("application/vnd.ipunplugged.rcprofile", "rcprofile"),
    VND_IREPOSITORY_PACKAGE_XML("application/vnd.irepository.package+xml", "irp"),
    VND_IS_XPR("application/vnd.is-xpr", "xpr"),
    VND_JAM("application/vnd.jam", "jam"),
    VND_JCP_JAVAME_MIDLET_RMS("application/vnd.jcp.javame.midlet-rms", "rms"),
    VND_JISP("application/vnd.jisp", "jisp"),
    VND_JOOST_JODA_ARCHIVE("application/vnd.joost.joda-archive", "joda"),
    VND_KAHOOTZ("application/vnd.kahootz", "ktr", "ktz"),
    VND_KDE_KARBON("application/vnd.kde.karbon", "karbon"),
    VND_KDE_KCHART("application/vnd.kde.kchart", "chrt"),
    VND_KDE_KFORMULA("application/vnd.kde.kformula", "kfo"),
    VND_KDE_KIVIO("application/vnd.kde.kivio", "flw"),
    VND_KDE_KONTOUR("application/vnd.kde.kontour", "kon"),
    VND_KDE_KPRESENTER("application/vnd.kde.kpresenter", "kpr", "kpt"),
    VND_KDE_KSPREAD("application/vnd.kde.kspread", "ksp"),
    VND_KDE_KWORD("application/vnd.kde.kword", "kwd", "kwt"),
    VND_KENAMEAAPP("application/vnd.kenameaapp", "htke"),
    VND_KIDSPIRATION("application/vnd.kidspiration", "kia"),
    VND_KINAR("application/vnd.kinar", "kne", "knp"),
    VND_KOAN("application/vnd.koan", "skd", "skm", "skp", "skt"),
    VND_KODAK_DESCRIPTOR("application/vnd.kodak-descriptor", "sse"),
    VND_LLAMAGRAPHICS_LIFE_BALANCE_DESKTOP("application/vnd.llamagraphics.life-balance.desktop", "lbd"),
    VND_LLAMAGRAPHICS_LIFE_BALANCE_EXCHANGE_XML("application/vnd.llamagraphics.life-balance.exchange+xml", "lbe"),
    VND_LOTUS_1_2_3("application/vnd.lotus-1-2-3", "123"),
    VND_LOTUS_APPROACH("application/vnd.lotus-approach", "apr"),
    VND_LOTUS_FREELANCE("application/vnd.lotus-freelance", "pre"),
    VND_LOTUS_NOTES("application/vnd.lotus-notes", "nsf"),
    VND_LOTUS_ORGANIZER("application/vnd.lotus-organizer", "org"),
    VND_LOTUS_SCREENCAM("application/vnd.lotus-screencam", "scm"),
    VND_LOTUS_WORDPRO("application/vnd.lotus-wordpro", "lwp"),
    VND_MACPORTS_PORTPKG("application/vnd.macports.portpkg", "portpkg"),
    VND_MCD("application/vnd.mcd", "mcd"),
    VND_MEDCALCDATA("application/vnd.medcalcdata", "mc1"),
    VND_MEDIASTATION_CDKEY("application/vnd.mediastation.cdkey", "cdkey"),
    VND_MFER("application/vnd.mfer", "mwf"),
    VND_MFMP("application/vnd.mfmp", "mfm"),
    VND_MICROGRAFX_FLO("application/vnd.micrografx.flo", "flo"),
    VND_MICROGRAFX_IGX("application/vnd.micrografx.igx", "igx"),
    VND_MIF("application/vnd.mif", "mif"),
    VND_MOBIUS_DAF("application/vnd.mobius.daf", "daf"),
    VND_MOBIUS_DIS("application/vnd.mobius.dis", "dis"),
    VND_MOBIUS_MBK("application/vnd.mobius.mbk", "mbk"),
    VND_MOBIUS_MQY("application/vnd.mobius.mqy", "mqy"),
    VND_MOBIUS_MSL("application/vnd.mobius.msl", "msl"),
    VND_MOBIUS_PLC("application/vnd.mobius.plc", "plc"),
    VND_MOBIUS_TXF("application/vnd.mobius.txf", "txf"),
    VND_MOPHUN_APPLICATION("application/vnd.mophun.application", "mpn"),
    VND_MOPHUN_CERTIFICATE("application/vnd.mophun.certificate", "mpc"),
    VND_MOZILLA_XUL_XML("application/vnd.mozilla.xul+xml", "xul"),
    VND_MS_ARTGALRY("application/vnd.ms-artgalry", "cil"),
    VND_MS_CAB_COMPRESSED("application/vnd.ms-cab-compressed", "cab"),
    VND_MS_EXCEL("application/vnd.ms-excel", "xla", "xlb", "xlc", "xlm", "xls", "xlt", "xlw"),
    VND_MS_EXCEL_ADDIN_MACROENABLED_12("application/vnd.ms-excel.addin.macroenabled.12", "xlam"),
    VND_MS_EXCEL_SHEET_BINARY_MACROENABLED_12("application/vnd.ms-excel.sheet.binary.macroenabled.12", "xlsb"),
    VND_MS_EXCEL_SHEET_MACROENABLED_12("application/vnd.ms-excel.sheet.macroenabled.12", "xlsm"),
    VND_MS_EXCEL_TEMPLATE_MACROENABLED_12("application/vnd.ms-excel.template.macroenabled.12", "xltm"),
    VND_MS_FONTOBJECT("application/vnd.ms-fontobject", "eot"),
    VND_MS_HTMLHELP("application/vnd.ms-htmlhelp", "chm"),
    VND_MS_IMS("application/vnd.ms-ims", "ims"),
    VND_MS_LRM("application/vnd.ms-lrm", "lrm"),
    VND_MS_PKI_SECCAT("application/vnd.ms-pki.seccat", "cat"),
    VND_MS_PKI_STL("application/vnd.ms-pki.stl", "stl"),
    VND_MS_POWERPOINT("application/vnd.ms-powerpoint", "pot", "ppa", "pps", "ppt", "pwz"),
    VND_MS_POWERPOINT_ADDIN_MACROENABLED_12("application/vnd.ms-powerpoint.addin.macroenabled.12", "ppam"),
    VND_MS_POWERPOINT_PRESENTATION_MACROENABLED_12("application/vnd.ms-powerpoint.presentation.macroenabled.12", "pptm"),
    VND_MS_POWERPOINT_SLIDE_MACROENABLED_12("application/vnd.ms-powerpoint.slide.macroenabled.12", "sldm"),
    VND_MS_POWERPOINT_SLIDESHOW_MACROENABLED_12("application/vnd.ms-powerpoint.slideshow.macroenabled.12", "ppsm"),
    VND_MS_POWERPOINT_TEMPLATE_MACROENABLED_12("application/vnd.ms-powerpoint.template.macroenabled.12", "potm"),
    VND_MS_PROJECT("application/vnd.ms-project", "mpp", "mpt"),
    VND_MS_WORD_DOCUMENT_MACROENABLED_12("application/vnd.ms-word.document.macroenabled.12", "docm"),
    VND_MS_WORD_TEMPLATE_MACROENABLED_12("application/vnd.ms-word.template.macroenabled.12", "dotm"),
    VND_MS_WORKS("application/vnd.ms-works", "wcm", "wdb", "wks", "wps"),
    VND_MS_WPL("application/vnd.ms-wpl", "wpl"),
    VND_MS_XPSDOCUMENT("application/vnd.ms-xpsdocument", "xps"),
    VND_MSEQ("application/vnd.mseq", "mseq"),
    VND_MUSICIAN("application/vnd.musician", "mus"),
    VND_MUVEE_STYLE("application/vnd.muvee.style", "msty"),
    VND_NEUROLANGUAGE_NLU("application/vnd.neurolanguage.nlu", "nlu"),
    VND_NOBLENET_DIRECTORY("application/vnd.noblenet-directory", "nnd"),
    VND_NOBLENET_SEALER("application/vnd.noblenet-sealer", "nns"),
    VND_NOBLENET_WEB("application/vnd.noblenet-web", "nnw"),
    VND_NOKIA_N_GAGE_DATA("application/vnd.nokia.n-gage.data", "ngdat"),
    VND_NOKIA_N_GAGE_SYMBIAN_INSTALL("application/vnd.nokia.n-gage.symbian.install", "n-gage"),
    VND_NOKIA_RADIO_PRESET("application/vnd.nokia.radio-preset", "rpst"),
    VND_NOKIA_RADIO_PRESETS("application/vnd.nokia.radio-presets", "rpss"),
    VND_NOVADIGM_EDM("application/vnd.novadigm.edm", "edm"),
    VND_NOVADIGM_EDX("application/vnd.novadigm.edx", "edx"),
    VND_NOVADIGM_EXT("application/vnd.novadigm.ext", "ext"),
    VND_OASIS_OPENDOCUMENT_CHART("application/vnd.oasis.opendocument.chart", "odc"),
    VND_OASIS_OPENDOCUMENT_CHART_TEMPLATE("application/vnd.oasis.opendocument.chart-template", "otc"),
    VND_OASIS_OPENDOCUMENT_DATABASE("application/vnd.oasis.opendocument.database", "odb"),
    VND_OASIS_OPENDOCUMENT_FORMULA("application/vnd.oasis.opendocument.formula", "odf"),
    VND_OASIS_OPENDOCUMENT_FORMULA_TEMPLATE("application/vnd.oasis.opendocument.formula-template", "odft"),
    VND_OASIS_OPENDOCUMENT_GRAPHICS("application/vnd.oasis.opendocument.graphics", "odg"),
    VND_OASIS_OPENDOCUMENT_GRAPHICS_TEMPLATE("application/vnd.oasis.opendocument.graphics-template", "otg"),
    VND_OASIS_OPENDOCUMENT_IMAGE("application/vnd.oasis.opendocument.image", "odi"),
    VND_OASIS_OPENDOCUMENT_IMAGE_TEMPLATE("application/vnd.oasis.opendocument.image-template", "oti"),
    VND_OASIS_OPENDOCUMENT_PRESENTATION("application/vnd.oasis.opendocument.presentation", "odp"),
    VND_OASIS_OPENDOCUMENT_PRESENTATION_TEMPLATE("application/vnd.oasis.opendocument.presentation-template", "otp"),
    VND_OASIS_OPENDOCUMENT_SPREADSHEET("application/vnd.oasis.opendocument.spreadsheet", "ods"),
    VND_OASIS_OPENDOCUMENT_SPREADSHEET_TEMPLATE("application/vnd.oasis.opendocument.spreadsheet-template", "ots"),
    VND_OASIS_OPENDOCUMENT_TEXT("application/vnd.oasis.opendocument.text", "odt"),
    VND_OASIS_OPENDOCUMENT_TEXT_MASTER("application/vnd.oasis.opendocument.text-master", "otm"),
    VND_OASIS_OPENDOCUMENT_TEXT_TEMPLATE("application/vnd.oasis.opendocument.text-template", "ott"),
    VND_OASIS_OPENDOCUMENT_TEXT_WEB("application/vnd.oasis.opendocument.text-web", "oth"),
    VND_OLPC_SUGAR("application/vnd.olpc-sugar", "xo"),
    VND_OMA_DD2_XML("application/vnd.oma.dd2+xml", "dd2"),
    VND_OPENOFFICEORG_EXTENSION("application/vnd.openofficeorg.extension", "oxt"),
    VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_PRESENTATION("application/vnd.openxmlformats-officedocument.presentationml.presentation", "pptx"),
    VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_SLIDE("application/vnd.openxmlformats-officedocument.presentationml.slide", "sldx"),
    VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_SLIDESHOW("application/vnd.openxmlformats-officedocument.presentationml.slideshow", "ppsx"),
    VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_TEMPLATE("application/vnd.openxmlformats-officedocument.presentationml.template", "potx"),
    VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_SHEET("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx"),
    VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_TEMPLATE("application/vnd.openxmlformats-officedocument.spreadsheetml.template", "xltx"),
    VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_DOCUMENT("application/vnd.openxmlformats-officedocument.wordprocessingml.document", "docx"),
    VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_TEMPLATE("application/vnd.openxmlformats-officedocument.wordprocessingml.template", "dotx"),
    VND_OSGI_DP("application/vnd.osgi.dp", "dp"),
    VND_PALM("application/vnd.palm", "oprc", "pdb", "pqa"),
    VND_PG_FORMAT("application/vnd.pg.format", "str"),
    VND_PG_OSASLI("application/vnd.pg.osasli", "ei6"),
    VND_PICSEL("application/vnd.picsel", "efif"),
    VND_POCKETLEARN("application/vnd.pocketlearn", "plf"),
    VND_POWERBUILDER6("application/vnd.powerbuilder6", "pbd"),
    VND_PREVIEWSYSTEMS_BOX("application/vnd.previewsystems.box", "box"),
    VND_PROTEUS_MAGAZINE("application/vnd.proteus.magazine", "mgz"),
    VND_PUBLISHARE_DELTA_TREE("application/vnd.publishare-delta-tree", "qps"),
    VND_PVI_PTID1("application/vnd.pvi.ptid1", "ptid"),
    VND_QUARK_QUARKXPRESS("application/vnd.quark.quarkxpress", "qwd", "qwt", "qxb", "qxd", "qxl", "qxt"),
    VND_RAR("application/vnd.rar", "rar"),
    VND_RECORDARE_MUSICXML("application/vnd.recordare.musicxml", "mxl"),
    VND_RECORDARE_MUSICXML_XML("application/vnd.recordare.musicxml+xml", "musicxml"),
    VND_RIM_COD("application/vnd.rim.cod", "cod"),
    VND_RN_REALMEDIA("application/vnd.rn-realmedia", "rm"),
    VND_ROUTE66_LINK66_XML("application/vnd.route66.link66+xml", "link66"),
    VND_SEEMAIL("application/vnd.seemail", "see"),
    VND_SEMA("application/vnd.sema", "sema"),
    VND_SEMD("application/vnd.semd", "semd"),
    VND_SEMF("application/vnd.semf", "semf"),
    VND_SHANA_INFORMED_FORMDATA("application/vnd.shana.informed.formdata", "ifm"),
    VND_SHANA_INFORMED_FORMTEMPLATE("application/vnd.shana.informed.formtemplate", "itp"),
    VND_SHANA_INFORMED_INTERCHANGE("application/vnd.shana.informed.interchange", "iif"),
    VND_SHANA_INFORMED_PACKAGE("application/vnd.shana.informed.package", "ipk"),
    VND_SIMTECH_MINDMAPPER("application/vnd.simtech-mindmapper", "twd", "twds"),
    VND_SMAF("application/vnd.smaf", "mmf"),
    VND_SMART_TEACHER("application/vnd.smart.teacher", "teacher"),
    VND_SOLENT_SDKM_XML("application/vnd.solent.sdkm+xml", "sdkd", "sdkm"),
    VND_SPOTFIRE_DXP("application/vnd.spotfire.dxp", "dxp"),
    VND_SPOTFIRE_SFS("application/vnd.spotfire.sfs", "sfs"),
    VND_SQLITE3("application/vnd.sqlite3", "db", "sqlite", "sqlite3", "db-wal", "sqlite-wal", "db-shm", "sqlite-shm"),
    VND_STAR_CALC("application/vnd.stardivision.calc", "sdc"),
    VND_STAR_DRAW("application/vnd.stardivision.draw", "sda"),
    VND_STAR_IMPRESS("application/vnd.stardivision.impress", "sdd"),
    VND_STAR_MATH("application/vnd.stardivision.math", "smf"),
    VND_STAR_WRITER("application/vnd.stardivision.writer", "sdw", "vor"),
    VND_STAR_WRITER_GLOBAL("application/vnd.stardivision.writer-global", "sgl"),
    VND_SUN_XML_CALC("application/vnd.sun.xml.calc", "sxc"),
    VND_SUN_XML_CALC_TEMPLATE("application/vnd.sun.xml.calc.template", "stc"),
    VND_SUN_XML_DRAW("application/vnd.sun.xml.draw", "sxd"),
    VND_SUN_XML_DRAW_TEMPLATE("application/vnd.sun.xml.draw.template", "std"),
    VND_SUN_XML_IMPRESS("application/vnd.sun.xml.impress", "sxi"),
    VND_SUN_XML_IMPRESS_TEMPLATE("application/vnd.sun.xml.impress.template", "sti"),
    VND_SUN_XML_MATH("application/vnd.sun.xml.math", "sxm"),
    VND_SUN_XML_WRITER("application/vnd.sun.xml.writer", "sxw"),
    VND_SUN_XML_WRITER_GLOBAL("application/vnd.sun.xml.writer.global", "sxg"),
    VND_SUN_XML_WRITER_TEMPLATE("application/vnd.sun.xml.writer.template", "stw"),
    VND_SUS_CALENDAR("application/vnd.sus-calendar", "sus", "susp"),
    VND_SVD("application/vnd.svd", "svd"),
    VND_SYMBIAN_INSTALL("application/vnd.symbian.install", "sis", "sisx"),
    VND_SYNCML_XML("application/vnd.syncml+xml", "xsm"),
    VND_SYNCML_DM_WBXML("application/vnd.syncml.dm+wbxml", "bdm"),
    VND_SYNCML_DM_XML("application/vnd.syncml.dm+xml", "xdm"),
    VND_TAO_INTENT_MODULE_ARCHIVE("application/vnd.tao.intent-module-archive", "tao"),
    VND_TMOBILE_LIVETV("application/vnd.tmobile-livetv", "tmo"),
    VND_TRID_TPT("application/vnd.trid.tpt", "tpt"),
    VND_TRISCAPE_MXS("application/vnd.triscape.mxs", "mxs"),
    VND_TRUEAPP("application/vnd.trueapp", "tra"),
    VND_UFDL("application/vnd.ufdl", "ufd", "ufdl"),
    VND_UIQ_THEME("application/vnd.uiq.theme", "utz"),
    VND_UMAJIN("application/vnd.umajin", "umj"),
    VND_UNITY("application/vnd.unity", "unityweb"),
    VND_UOML_XML("application/vnd.uoml+xml", "uoml"),
    VND_VCX("application/vnd.vcx", "vcx"),
    VND_VISIO("application/vnd.visio", "vsd", "vss", "vst", "vsw", "vsdx", "vssx", "vstx", "vssm", "vstm"),
    VND_VISIONARY("application/vnd.visionary", "vis"),
    VND_VSF("application/vnd.vsf", "vsf"),
    VND_WAP_SIC("application/vnd.wap.sic", "sic"),
    VND_WAP_SLC("application/vnd.wap.slc", "slc"),
    VND_WAP_WBXML("application/vnd.wap.wbxml", "wbxml"),
    VND_WAP_WMLC("application/vnd.wap.wmlc", "wmlc"),
    VND_WAP_WMLSCRIPTC("application/vnd.wap.wmlscriptc", "wmlsc"),
    VND_WEBTURBO("application/vnd.webturbo", "wtb"),
    VND_WORDPERFECT("application/vnd.wordperfect", "wpd"),
    VND_WQD("application/vnd.wqd", "wqd"),
    VND_WT_STF("application/vnd.wt.stf", "stf"),
    VND_XARA("application/vnd.xara", "xar"),
    VND_XFDL("application/vnd.xfdl", "xfdl"),
    VND_YAMAHA_HV_DIC("application/vnd.yamaha.hv-dic", "hvd"),
    VND_YAMAHA_HV_SCRIPT("application/vnd.yamaha.hv-script", "hvs"),
    VND_YAMAHA_HV_VOICE("application/vnd.yamaha.hv-voice", "hvp"),
    VND_YAMAHA_OPENSCOREFORMAT("application/vnd.yamaha.openscoreformat", "osf"),
    VND_YAMAHA_OPENSCOREFORMAT_OSFPVG_XML("application/vnd.yamaha.openscoreformat.osfpvg+xml", "osfpvg"),
    VND_YAMAHA_SMAF_AUDIO("application/vnd.yamaha.smaf-audio", "saf"),
    VND_YAMAHA_SMAF_PHRASE("application/vnd.yamaha.smaf-phrase", "spf"),
    VND_YELLOWRIVER_CUSTOM_MENU("application/vnd.yellowriver-custom-menu", "cmp"),
    VND_ZUL("application/vnd.zul", "zir", "zirz"),
    VND_ZZAZZ_DECK_XML("application/vnd.zzazz.deck+xml", "zaz"),
    VOICEXML_XML("application/voicexml+xml", "vxml"),
    WASM("application/wasm", "wasm"),
    WINHLP("application/winhlp", "hlp"),
    WSDL_XML("application/wsdl+xml", "wsdl"),
    WSPOLICY_XML("application/wspolicy+xml", "wspolicy"),
    X_7Z_COMPRESSED("application/x-7z-compressed", "7z"),
    X_ABIWORD("application/x-abiword", "abw", "zabw", "abw.gz"),
    X_ACE_COMPRESSED("application/x-ace-compressed", "ace"),
    X_AUTHORWARE_BIN("application/x-authorware-bin", "aab", "u32", "vox", "x32"),
    X_AUTHORWARE_MAP("application/x-authorware-map", "aam"),
    X_AUTHORWARE_SEG("application/x-authorware-seg", "aas"),
    X_BCPIO("application/x-bcpio", "bcpio"),
    X_BITTORRENT("application/x-bittorrent", "torrent"),
    X_BZIP("application/x-bzip", "bz"),
    X_BZIP2("application/x-bzip2", "boz", "bz2"),
    X_CDLINK("application/x-cdlink", "vcd"),
    X_CHAT("application/x-chat", "chat"),
    X_CHESS_PGN("application/x-chess-pgn", "pgn"),
    X_CPIO("application/x-cpio", "cpio"),
    X_CSH("application/x-csh", "csh"),
    X_DEBIAN_PACKAGE("application/x-debian-package", "deb", "udeb"),
    X_DIRECTOR("application/x-director", "cct", "cst", "cxt", "dcr", "dir", "dxr", "fgd", "swa", "w3d"),
    X_DOOM("application/x-doom", "wad"),
    X_DTBNCX_XML("application/x-dtbncx+xml", "ncx"),
    X_DTBOOK_XML("application/x-dtbook+xml", "dtb"),
    X_DTBRESOURCE_XML("application/x-dtbresource+xml", "res"),
    X_DVI("application/x-dvi", "dvi"),
    X_FONT_BDF("application/x-font-bdf", "bdf"),
    X_FONT_GHOSTSCRIPT("application/x-font-ghostscript", "gsf"),
    X_FONT_LINUX_PSF("application/x-font-linux-psf", "psf"),
    X_FONT_OTF("application/x-font-otf", "otf"),
    X_FONT_PCF("application/x-font-pcf", "pcf"),
    X_FONT_SNF("application/x-font-snf", "snf"),
    X_FONT_TTF("application/x-font-ttf", "ttc", "ttf"),
    X_FONT_TYPE1("application/x-font-type1", "afm", "pfa", "pfb", "pfm"),
    X_FUTURESPLASH("application/x-futuresplash", "spl"),
    X_GNUMERIC("application/x-gnumeric", "gnumeric"),
    X_GTAR("application/x-gtar", "gtar"),
    X_GZIP("application/x-gzip", "gz", "tgz"),
    X_HDF("application/x-hdf", "hdf"),
    X_ISO9660_IMAGE("application/x-iso9660-image", "iso", "isoimg", "cdr"),
    X_JAVA_JNLP_FILE("application/x-java-jnlp-file", "jnlp"),
    X_KILLUSTRATOR("application/x-killustrator", "kil"),
    X_KRITA("application/x-krita", "kra", "krz"),
    X_LATEX("application/x-latex", "latex"),
    X_MOBIPOCKET_EBOOK("application/x-mobipocket-ebook", "mobi", "prc"),
    X_MS_APPLICATION("application/x-ms-application", "application"),
    X_MS_WMD("application/x-ms-wmd", "wmd"),
    X_MS_WMZ("application/x-ms-wmz", "wmz"),
    X_MS_XBAP("application/x-ms-xbap", "xbap"),
    X_MSACCESS("application/x-msaccess", "mdb"),
    X_MSBINDER("application/x-msbinder", "obd"),
    X_MSCARDFILE("application/x-mscardfile", "crd"),
    X_MSCLIP("application/x-msclip", "clp"),
    X_MSDOWNLOAD("application/x-msdownload", "bat", "com", "dll", "exe", "msi"),
    X_MSMEDIAVIEW("application/x-msmediaview", "m13", "m14", "mvb"),
    X_MSMETAFILE("application/x-msmetafile", "wmf"),
    X_MSMONEY("application/x-msmoney", "mny"),
    X_MSPUBLISHER("application/x-mspublisher", "pub"),
    X_MSSCHEDULE("application/x-msschedule", "scd"),
    X_MSTERMINAL("application/x-msterminal", "trm"),
    X_MSWRITE("application/x-mswrite", "wri"),
    X_NETCDF("application/x-netcdf", "cdf", "nc"),
    X_PERL("application/x-perl", "pm", "pl"),
    X_PKCS12("application/x-pkcs12", "p12", "pfx"),
    X_PKCS7_CERTIFICATES("application/x-pkcs7-certificates", "p7b", "spc"),
    X_PKCS7_CERTREQRESP("application/x-pkcs7-certreqresp", "p7r"),
    X_RAR_COMPRESSED("application/x-rar-compressed", "rar"),
    X_REDHAT_PACKAGE_MANAGER("application/x-redhat-package-manager", "rpa"),
    X_RPM("application/x-rpm", "rpm"),
    X_SH("application/x-sh", "sh"),
    X_SHAR("application/x-shar", "shar"),
    X_SHELLSCRIPT("application/x-shellscript", "sh"),
    X_SHOCKWAVE_FLASH("application/x-shockwave-flash", "swf"),
    X_SILVERLIGHT_APP("application/x-silverlight-app", "xap"),
    X_STUFFIT("application/x-stuffit", "sit"),
    X_STUFFITX("application/x-stuffitx", "sitx"),
    X_SV4CPIO("application/x-sv4cpio", "sv4cpio"),
    X_SV4CRC("application/x-sv4crc", "sv4crc"),
    X_TAR("application/x-tar", "tar"),
    X_TCL("application/x-tcl", "tcl"),
    X_TEX("application/x-tex", "tex"),
    X_TEX_TFM("application/x-tex-tfm", "tfm"),
    X_TEXINFO("application/x-texinfo", "texi", "texinfo"),
    X_TRASH("application/x-trash"),
    X_USTAR("application/x-ustar", "ustar"),
    X_WAIS_SOURCE("application/x-wais-source", "src"),
    X_X509_CA_CERT("application/x-x509-ca-cert", "crt", "der"),
    X_XFIG("application/x-xfig", "fig"),
    X_XPINSTALL("application/x-xpinstall", "xpi"),
    X_ZIP_COMPRESSED("application/x-zip-compressed", "zip"),
    XENC_XML("application/xenc+xml", "xenc"),
    XHTML_XML("application/xhtml+xml", "xht", "xhtml"),
    XML("application/xml", "xml", "xpdl", "xsl"),
    XML_DTD("application/xml-dtd", "dtd"),
    XOP_XML("application/xop+xml", "xop"),
    XSLT_XML("application/xslt+xml", "xslt"),
    XSPF_XML("application/xspf+xml", "xspf"),
    XV_XML("application/xv+xml", "mxml", "xhvml", "xvm", "xvml"),
    YAML("application/yaml", "yaml", "yml"),
    ZIP("application/zip", "zip"),
    ZIP_COMPRESSED("application/zip-compressed", "zip"),

    // === AUDIO ===
    _3GPP2_AUDIO("audio/3gpp2", "3g2"),
    AAC("audio/aac", "aac", "m4a"),
    AACP("audio/aacp", "aacp"),
    ADPCM("audio/adpcm", "adp"),
    AIFF("audio/aiff", "aiff", "aif", "aff"),
    BASIC("audio/basic", "au", "snd"),
    FLAC("audio/flac", "flac"),
    MIDI("audio/midi", "kar", "mid", "midi", "rmi"),
    MP4_AUDIO("audio/mp4", "mp4", "m4a", "m4b", "m4p", "m4r", "m4v", "mp4v", "3gp", "3g2", "3ga", "3gpa", "3gpp", "3gpp2", "3gp2"),
    MP4A_LATM("audio/mp4a-latm"),
    MPEG_AUDIO("audio/mpeg", "m2a", "m3a", "mp2", "mp2a", "mp3", "mpga"),
    OGG_AUDIO("audio/ogg", "oga", "ogg", "spx"),
    OPUS("audio/opus", "opus"),
    VND_DIGITAL_WINDS("audio/vnd.digital-winds", "eol"),
    VND_DTS("audio/vnd.dts", "dts"),
    VND_DTS_HD("audio/vnd.dts.hd", "dtshd"),
    VND_LUCENT_VOICE("audio/vnd.lucent.voice", "lvp"),
    VND_MS_PLAYREADY_MEDIA_PYA("audio/vnd.ms-playready.media.pya", "pya"),
    VND_NUERA_ECELP4800("audio/vnd.nuera.ecelp4800", "ecelp4800"),
    VND_NUERA_ECELP7470("audio/vnd.nuera.ecelp7470", "ecelp7470"),
    VND_NUERA_ECELP9600("audio/vnd.nuera.ecelp9600", "ecelp9600"),
    WAV("audio/wav", "wav"),
    WEBM_AUDIO("audio/webm", "weba"),
    X_MATROSKA_AUDIO("audio/x-matroska", "mka"),
    X_MPEGURL("audio/x-mpegurl", "m3u"),
    X_MS_WAX("audio/x-ms-wax", "wax"),
    X_MS_WMA("audio/x-ms-wma", "wma"),
    X_PN_REALAUDIO("audio/x-pn-realaudio", "ra", "ram"),
    X_PN_REALAUDIO_PLUGIN("audio/x-pn-realaudio-plugin", "rmp"),

    // === IMAGE ===
    AVIF("image/avif", "avif"),
    AVIF_SEQUENCE("image/avif-sequence", "avifs"),
    BMP("image/bmp", "bmp"),
    CGM("image/cgm", "cgm"),
    G3FAX("image/g3fax", "g3"),
    GIF("image/gif", "gif"),
    HEIC("image/heic", "heif", "heic"),
    IEF("image/ief", "ief"),
    JPEG("image/jpeg", "jpe", "jpeg", "jpg", "pjpg", "jfif", "jfif-tbnl", "jif"),
    PJPEG("image/pjpeg", "jpe", "jpeg", "jpg", "pjpg", "jfi", "jfif", "jfif-tbnl", "jif"),
    PNG("image/png", "png"),
    PRS_BTIF("image/prs.btif", "btif"),
    SVG_XML("image/svg+xml", "svg", "svgz"),
    TIFF("image/tiff", "tif", "tiff"),
    VND_ADOBE_PHOTOSHOP("image/vnd.adobe.photoshop", "psd"),
    VND_DJVU("image/vnd.djvu", "djv", "djvu"),
    VND_DWG("image/vnd.dwg", "dwg"),
    VND_DXF("image/vnd.dxf", "dxf"),
    VND_FASTBIDSHEET("image/vnd.fastbidsheet", "fbs"),
    VND_FPX("image/vnd.fpx", "fpx"),
    VND_FST("image/vnd.fst", "fst"),
    VND_FUJIXEROX_EDMICS_MMR("image/vnd.fujixerox.edmics-mmr", "mmr"),
    VND_FUJIXEROX_EDMICS_RLC("image/vnd.fujixerox.edmics-rlc", "rlc"),
    VND_MS_MODI("image/vnd.ms-modi", "mdi"),
    VND_NET_FPX("image/vnd.net-fpx", "npx"),
    VND_WAP_WBMP("image/vnd.wap.wbmp", "wbmp"),
    VND_XIFF("image/vnd.xiff", "xif"),
    WEBP("image/webp", "webp"),
    X_ADOBE_DNG("image/x-adobe-dng", "dng"),
    X_CANON_CR2("image/x-canon-cr2", "cr2"),
    X_CANON_CRW("image/x-canon-crw", "crw"),
    X_CMU_RASTER("image/x-cmu-raster", "ras"),
    X_CMX("image/x-cmx", "cmx"),
    X_EPSON_ERF("image/x-epson-erf", "erf"),
    X_FREEHAND("image/x-freehand", "fh", "fh4", "fh5", "fh7", "fhc"),
    X_FUJI_RAF("image/x-fuji-raf", "raf"),
    X_ICNS("image/x-icns", "icns"),
    X_ICON("image/x-icon", "ico"),
    X_KODAK_DCR("image/x-kodak-dcr", "dcr"),
    X_KODAK_K25("image/x-kodak-k25", "k25"),
    X_KODAK_KDC("image/x-kodak-kdc", "kdc"),
    X_MINOLTA_MRW("image/x-minolta-mrw", "mrw"),
    X_NIKON_NEF("image/x-nikon-nef", "nef"),
    X_OLYMPUS_ORF("image/x-olympus-orf", "orf"),
    X_PANASONIC_RAW("image/x-panasonic-raw", "raw", "rw2", "rwl"),
    X_PCX("image/x-pcx", "pcx"),
    X_PENTAX_PEF("image/x-pentax-pef", "pef", "ptx"),
    X_PICT("image/x-pict", "pct", "pic"),
    X_PORTABLE_ANYMAP("image/x-portable-anymap", "pnm"),
    X_PORTABLE_BITMAP("image/x-portable-bitmap", "pbm"),
    X_PORTABLE_GRAYMAP("image/x-portable-graymap", "pgm"),
    X_PORTABLE_PIXMAP("image/x-portable-pixmap", "ppm"),
    X_RGB("image/x-rgb", "rgb"),
    X_SIGMA_X3F("image/x-sigma-x3f", "x3f"),
    X_SONY_ARW("image/x-sony-arw", "arw"),
    X_SONY_SR2("image/x-sony-sr2", "sr2"),
    X_SONY_SRF("image/x-sony-srf", "srf"),
    X_XBITMAP("image/x-xbitmap", "xbm"),
    X_XPIXMAP("image/x-xpixmap", "xpm"),
    X_XWINDOWDUMP("image/x-xwindowdump", "xwd"),

    // === VIDEO ===
    _3GPP("video/3gpp", "3gp"),
    _3GPP2("video/3gpp2", "3g2"),
    H261("video/h261", "h261"),
    H263("video/h263", "h263"),
    H264("video/h264", "h264"),
    JPEGV("video/jpeg", "jpgv"),
    JPM("video/jpm", "jpgm", "jpm"),
    MJ2("video/mj2", "mj2", "mjp2"),
    MP2T("video/mp2t", "ts"),
    MP4("video/mp4", "mp4", "mp4v", "mpg4"),
    MPEG("video/mpeg", "m1v", "m2v", "mpa", "mpe", "mpeg", "mpg"),
    OGG("video/ogg", "ogv"),
    QUICKTIME("video/quicktime", "mov", "qt"),
    VND_FVT("video/vnd.fvt", "fvt"),
    VND_MPEGURL("video/vnd.mpegurl", "m4u", "mxu"),
    VND_MS_PLAYREADY_MEDIA_PYV("video/vnd.ms-playready.media.pyv", "pyv"),
    VND_VIVO("video/vnd.vivo", "viv"),
    WEBM("video/webm", "webm"),
    X_F4V("video/x-f4v", "f4v"),
    X_FLI("video/x-fli", "fli"),
    X_FLV("video/x-flv", "flv"),
    X_M4V("video/x-m4v", "m4v"),
    X_MATROSKA("video/x-matroska", "mkv"),
    X_MS_ASF("video/x-ms-asf", "asf", "asx"),
    X_MS_WM("video/x-ms-wm", "wm"),
    X_MS_WMV("video/x-ms-wmv", "wmv"),
    X_MS_WMX("video/x-ms-wmx", "wmx"),
    X_MS_WVX("video/x-ms-wvx", "wvx"),
    X_MSVIDEO("video/x-msvideo", "avi"),
    X_SGI_MOVIE("video/x-sgi-movie", "movie"),

    // === TEXT ===
    CALENDAR("text/calendar", "ics", "ifb"),
    CSS("text/css", "css"),
    CSV("text/csv", "csv"),
    HTML("text/html", "htm", "html"),
    JAVASCRIPT("text/javascript", "js"),
    MARKDOWN("text/markdown", "md", "markdown", "mdown", "markdn"),
    MATHML("text/mathml", "mathml", "mml"),
    PLAIN("text/plain", "conf", "def", "diff", "in", "ksh", "list", "log", "pl", "text", "txt"),
    PRS_LINES_TAG("text/prs.lines.tag", "dsc"),
    RICHTEXT("text/richtext", "rtx"),
    SGML("text/sgml", "sgm", "sgml"),
    TAB_SEPARATED_VALUES("text/tab-separated-values", "tsv"),
    TROFF("text/troff", "man", "me", "ms", "roff", "t", "tr"),
    URI_LIST("text/uri-list", "uri", "uris", "urls"),
    VND_CURL("text/vnd.curl", "curl"),
    VND_CURL_DCURL("text/vnd.curl.dcurl", "dcurl"),
    VND_CURL_MCURL("text/vnd.curl.mcurl", "mcurl"),
    VND_CURL_SCURL("text/vnd.curl.scurl", "scurl"),
    VND_FLY("text/vnd.fly", "fly"),
    VND_FMI_FLEXSTOR("text/vnd.fmi.flexstor", "flx"),
    VND_GRAPHVIZ("text/vnd.graphviz", "gv"),
    VND_IN3D_3DML("text/vnd.in3d.3dml", "3dml"),
    VND_IN3D_SPOT("text/vnd.in3d.spot", "spot"),
    VND_SUN_J2ME_APP_DESCRIPTOR("text/vnd.sun.j2me.app-descriptor", "jad"),
    VND_WAP_SI("text/vnd.wap.si", "si"),
    VND_WAP_SL("text/vnd.wap.sl", "sl"),
    VND_WAP_WML("text/vnd.wap.wml", "wml"),
    VND_WAP_WMLSCRIPT("text/vnd.wap.wmlscript", "wmls"),
    X_ASM("text/x-asm", "asm", "s"),
    X_C("text/x-c", "c", "cc", "cpp", "cxx", "dic", "h", "hh"),
    X_FORTRAN("text/x-fortran", "f", "f77", "f90", "for"),
    X_JAVA_SOURCE("text/x-java-source", "java"),
    X_PASCAL("text/x-pascal", "p", "pas", "pp", "inc"),
    X_PYTHON("text/x-python", "py", "pyc", "pyo", "pyd", "whl"),
    X_SETEXT("text/x-setext", "etx"),
    X_UUENCODE("text/x-uuencode", "uu"),
    X_VCALENDAR("text/x-vcalendar", "vcs"),
    X_VCARD("text/x-vcard", "vcf"),

    // === MESSAGE ===
    RFC822("message/rfc822", "eml", "mht", "mhtml", "mime", "nws"),

    // === MODEL ===
    IGES("model/iges", "iges", "igs"),
    MESH("model/mesh", "mesh", "msh", "silo"),
    VND_DWF("model/vnd.dwf", "dwf"),
    VND_GDL("model/vnd.gdl", "gdl"),
    VND_GTW("model/vnd.gtw", "gtw"),
    VND_MTS("model/vnd.mts", "mts"),
    VND_VTU("model/vnd.vtu", "vtu"),
    VRML("model/vrml", "vrml", "wrl"),

    // === CHEMICAL ===
    X_CDX("chemical/x-cdx", "cdx"),
    X_CIF("chemical/x-cif", "cif"),
    X_CMDF("chemical/x-cmdf", "cmdf"),
    X_CML("chemical/x-cml", "cml"),
    X_CSML("chemical/x-csml", "csml"),
    X_XYZ("chemical/x-xyz", "xyz"),

    // === FONT ===
    OTF("font/otf", "otf"),
    WOFF("font/woff", "woff"),
    WOFF2("font/woff2", "woff2"),

    // === X-CONFERENCE ===
    X_COOLTALK("x-conference/x-cooltalk", "ice"),

    // === TEST ===
    TEST_MIMETYPE("test/mimetype", "test");

    private final String mimeType;
    private final Set<String> extensions;

    MimeType(String mimeType, String... extensions) {
        this.mimeType = mimeType;
        this.extensions = Set.of(extensions);
    }

    public String getMimeType() {
        return mimeType;
    }

    public String getPrimaryExtension() {
        return extensions.isEmpty() ? "" : extensions.iterator().next();
    }

    public Set<String> getExtensions() {
        return Collections.unmodifiableSet(extensions);
    }

    // === MAPA ESTÁTICO PARA BUSCA RÁPIDA ===
    private static final Map<String, MimeType> EXTENSION_MAP;

    static {
        Map<String, MimeType> map = new HashMap<>();
        for (MimeType mt : values()) {
            for (String ext : mt.extensions) {
                map.put(ext.toLowerCase(), mt);
            }
        }
        EXTENSION_MAP = Collections.unmodifiableMap(map);
    }

    /**
     * Busca o MimeType pela extensão do arquivo (case-insensitive).
     * @param extension Extensão com ou sem ponto (ex: "pdf", ".pdf", "PDF")
     * @return MimeType ou null se não encontrado
     */
    public static MimeType fromExtension(String extension) {
        if (extension == null || extension.isBlank()) return null;
        String ext = extension.trim().toLowerCase();
        if (ext.startsWith(".")) {
            ext = ext.substring(1);
        }
        return EXTENSION_MAP.get(ext);
    }

    /**
     * Retorna todos os MIME types que contêm a extensão (útil para debug)
     */
    public static List<MimeType> findByExtension(String extension) {
        return EXTENSION_MAP.entrySet().stream()
                .filter(e -> e.getKey().equals(extension.toLowerCase().replaceFirst("^\\.", "")))
                .map(Map.Entry::getValue)
                .collect(Collectors.toList());
    }
}
