<project 	xmlns="http://maven.apache.org/POM/4.0.0" 
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
			xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
>
	<modelVersion>4.0.0</modelVersion>
	<!-- PARENT INFO -->
	<parent>
		<groupId>org.tedros</groupId>
		<artifactId>tedrosbox</artifactId>
		<version>17-0.0.1</version>
	</parent>
	
	<!-- PROJECT -->
	<artifactId>tdrs-miscellaneous</artifactId>
  	<packaging>pom</packaging>
  	
  	<name>tdrs-miscellaneous</name>
  	<description>The tedros miscellaneous projects</description>
	
  	<!-- BUILD -->
  	<build>
    	<plugins>
      		<plugin>
        		<groupId>org.apache.maven.plugins</groupId>
        		<artifactId>maven-compiler-plugin</artifactId>
        		<version>${compiler.plugin}</version>
        		<configuration>
          			<source>${java.version}</source>
          			<target>${java.version}</target>
        		</configuration>
      		</plugin>
  		</plugins>
 	</build>
 
 	<!-- MODULES -->
	<modules>
		<module>tedros-util</module>
		<module>tedros-integration</module>
	</modules>
  
</project>