package org.tedros.tools.module.ai.function;

import org.slf4j.Logger;
import org.tedros.ai.TFunctionHelper;
import org.tedros.ai.function.TFunction;
import org.tedros.ai.function.model.Response;
import org.tedros.ai.function.model.ViewPath;
import org.tedros.api.form.ITFieldBox;
import org.tedros.api.form.ITModelForm;
import org.tedros.api.presenter.view.ITView;
import org.tedros.core.context.TViewDescriptor;
import org.tedros.core.context.TedrosAppManager;
import org.tedros.fx.presenter.dynamic.TDynaPresenter;
import org.tedros.fx.presenter.model.behavior.TViewBehavior;
import org.tedros.tools.module.ai.model.HtmlMessageViewerMV;
import org.tedros.tools.module.ai.model.HtmlMessageViewerModel;
import org.tedros.util.TLoggerUtil;

import javafx.application.Platform;
import javafx.scene.web.WebView;

public class ShowHtmlAiResponse extends TFunction<HtmlContent> {
	
	private static final Logger LOGGER = TLoggerUtil.getLogger(ShowHtmlAiResponse.class);
	
	private static final String HTML_RENDERED_SUCCESSFULLY = "HTML Rendered Successfully. DO NOT call this function again for this content. Proceed with text response or stop.";
	
	private static final String PROMPT = """
		    This function is responsible for displaying HTML content generated by the AI directly in the system interface.

		    Purpose:
		    - Render dynamic HTML fragments created by the AI to provide visually organized responses.

		    Usage Context:
		    - Call this function when the response requires formatting (tables, lists, cards, diagrams) better suited for HTML than plain text.
		    - The target view 'Teros AI Response' acts as a direct HTML renderer.

		    CRITICAL OUTPUT RULES (Follow Strictly):
		    1. **RAW HTML ONLY**: You must return a raw HTML string.
		    2. **NO ESCAPING**: Do NOT escape HTML tags. For example, return "<div>" (CORRECT), never "&lt;div&gt;" (WRONG).
		    3. **NO MARKDOWN**: Do NOT wrap the output in Markdown code blocks (e.g., ```html ... ```). Do NOT use backticks.
		    4. **NO DOCUMENT TAGS**: Do NOT include <html>, <head>, <body>, or <script>.
		    5. **MERMAID DIAGRAMS**: To insert diagrams, use exactly: <div class="mermaid">...syntax...</div>.

		    Content Guidelines:
		    - Use standard HTML5 tags (div, h3, p, ul, table, strong, span).
		    - Use inline CSS for styling to ensure it looks good on a dark background.
		    - Ensure the content is safe for insertion via 'innerHTML'.

		    Example of CORRECT call:
		    show_html_content(htmlContent="<div style='padding:10px;'><h3>Title</h3><p>Content here.</p></div>")

		    Example of WRONG call (Do NOT do this):
		    show_html_content(htmlContent="```html\n&lt;div&gt;...&lt;/div&gt;\n```")
		    """;
	
	public ShowHtmlAiResponse() {
		super("show_html_content", PROMPT, HtmlContent.class, 
				v->{
					LOGGER.info("Conteudo HTML recebido: {}",v.htmlContent());
					return run(v); 
				});
	}

	@SuppressWarnings({ "rawtypes", "unchecked" })
	private static Response run(HtmlContent v) {
		TedrosAppManager manager = TedrosAppManager.getInstance();
		
		ITView<TDynaPresenter> vw = manager.getCurrentView();
		
		if(vw==null || vw.gettPresenter().getModelViewClass()!=HtmlMessageViewerMV.class) {
			
			TViewDescriptor vd = manager.getViewDescriptor(HtmlMessageViewerMV.class, HtmlMessageViewerModel.class);
			
			ViewPath path = new ViewPath();
			path.setViewPath(vd.getPath());
			
			LOGGER.info("Tentando abrir a view: {}", path.getViewPath());
			
			manager.listenView(c-> run(v), path.getViewPath());
			
			TFunctionHelper.callUpViewFunction().getCallback().apply(path);
			
			return new Response(HTML_RENDERED_SUCCESSFULLY);
		} else {
		
			TDynaPresenter p = vw.gettPresenter();
			 
			Platform.runLater(()->{						
				
				ITModelForm form = ((TViewBehavior) p.getBehavior()).getForm();
				
				WebViewBridge webViewBridge = form.gettObjectRepository().get("webviewbridge");
				
				if(webViewBridge==null) {							
					ITFieldBox fdbox = form.gettFieldBox("webContent");
					WebView wv = (WebView) fdbox.gettControl();
					webViewBridge = new WebViewBridge(wv);
					form.gettObjectRepository().add("webviewbridge", webViewBridge);
				}
				
				// 1. Limpeza defensiva antes de processar
                String cleanContent = sanitizeAiOutput(v.htmlContent());
				
				webViewBridge.run(cleanContent);
				
			});
			
			return new Response(HTML_RENDERED_SUCCESSFULLY);
		}
	}	
	
	// Método auxiliar para limpar "sujeiras" comuns do modelo
	private static String sanitizeAiOutput(String input) {
	    if (input == null) return "";
	    
	    String result = input;

	    // 1. Remove blocos de código Markdown (```html ou ```)
	    if (result.startsWith("```html")) {
	        result = result.substring(7);
	    } else if (result.startsWith("```")) {
	        result = result.substring(3);
	    }
	    if (result.endsWith("```")) {
	        result = result.substring(0, result.length() - 3);
	    }

	    // 2. Desfaz o escape de tags HTML básicas se o modelo tiver escapado tudo
	    // Isso verifica se o inicio parece um html escapado (ex: &lt;div)
	    if (result.trim().startsWith("&lt;") && result.contains("&gt;")) {
	        result = result.replace("&lt;", "<")
	                       .replace("&gt;", ">")
	                       .replace("&quot;", "\"")
	                       .replace("&amp;", "&");
	    }
	    
	    return result.trim();
	}

}