version: '3.8'

services:
  tomee1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tedros-tomee1
    restart: always
    environment:
      - TZ=America/Sao_Paulo
    depends_on:
      - h2db
      - mongodb
    networks:
      - tedros-net

  tomee2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tedros-tomee2
    restart: always
    environment:
      - TZ=America/Sao_Paulo
    depends_on:
      - h2db
      - mongodb
    networks:
      - tedros-net

  h2db:
    image: oscarfonts/h2:1.4.199
    container_name: tedros-h2db
    restart: always
    environment:
      - H2_OPTIONS=-tcpAllowOthers -baseDir /opt/h2-data
    ports:
      - "1521:1521"
    volumes:
      - h2_data:/opt/h2-data
    networks:
      - tedros-net

  mongodb:
    image: mongo:8.0
    container_name: tedros-mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - tedros-net

  nginx:
    image: nginx:latest
    container_name: tedros-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/letsencrypt:ro
    depends_on:
      - tomee1
      - tomee2
    networks:
      - tedros-net

volumes:
  h2_data:
  mongo_data:


networks:
  tedros-net:
    driver: bridge
